### ISSUE TITLE
basic check failed

### ISSUE THREAD

**Issue by shibinraj** [rkpunjal/sql-injection-safe#1]
I am writing a  program  to generate dynamic queries based on the input user given for a search. There the user select the field and defines the condition.So I cannot use parametarised queries. So I used your library
 And am checking the user input field with SqlSafeUtil.isSqlInjectionSafe("my-string-value")
I have verified some condition such as TABLE,UPDATE ,DELETE etc in that util. all are working fine.
But one basic check "OR 1=1" fails and it return true status. Any solution?

**Comment by rkpunjal** [comment]
okay. I shall check and get back with a solution soon

**Comment by rkpunjal** [comment]
@shibinraj  can you show me what it is the string value that you are actually passing in to SqlSafeUtil.isSqlInjectionSafe(<what is your string>)?
Then I can clearly know what's happening here.

**Comment by rkpunjal** [comment]
no worries! understood the issue

**Comment by rkpunjal** [comment]
@shibinraj. I have fixed it now  :-)

malicious data of the nature as below will not go through now.
```
                " OR false ",
                " OR true ",
                " and true ",
                " OR equals true ",
                " OR not equals true ",
                " OR equals false ",
                " and equals false ",
                " OR 1=1",
                " and 1=1",
                " OR column1=COLUMN1",
                " OR column1 = COLUMN1",
                " OR column1!=COLUMN1",
                " OR column1<>COLUMN1",
                " OR colu_mn1=COL_UMN1",
                " OR 'A'='A'",
                " OR '1afA'='2fadfA'",
                " OR 1=1 OR 2=2",
                " OR 1=1 and 2=2",
                " and 1=1 and 2=2",
                " and 1=1 or 2=2",
```

Thank you for the wonderful input.
This makes the library more efficient :-)

**Comment by rkpunjal** [comment]
Feel free to use the latest version.  

Feel free to let me know if you have anymore suggestions, issues or inputs

```
<dependency>
   <groupId>com.github.rkpunjal.sqlsafe</groupId>
   <artifactId>sql-injection-safe</artifactId>
   <version>1.0.1</version>
</dependency>
```

**Comment by shibinraj** [comment]
The files downloaded as in the following name in my maven repository.
sql-injection-safe-1.0.1.jar.lastUpdated
sql-injection-safe-1.0.1.pom.lastUpdated
I resolved it by changing the name.    

Thank you for your update

**Comment by rkpunjal** [comment]
I see that the jar is properly available in the nexus repository.
Anyway I shall check again. Thanks

**Comment by shibinraj** [comment]
But the import also showing error. I tried as follows 
import **com.github**.rkpunjal.sqlsafe.SQLInjectionSafe;
import **com.github**.rkpunjal.sqlsafe.SqlSafeUtil;

the bold part showing the error

And I verified the downloaded jar  sql-injection-safe-1.0.1.jar .Its only having 1kb
but the version 1.0.0 have 7kb

**Comment by rkpunjal** [comment]
Should be available now. Could you check now ? and let me know ...

**Comment by rkpunjal** [comment]
remember to cleanup your old jars that you obtained by renaming ...

**Comment by shibinraj** [comment]
I have verified the Library. Now its working with the string " ' ' OR 1=1"  and all with you listed above.
But the string like UPDATE, DELETE etc which were working before showing error now. It return true while checking.  You missed something?

**Comment by rkpunjal** [comment]
That's strange, because the unit-tests verify that and they pass.
Can you send me an example of your usage that is failing

**Comment by shibinraj** [comment]
the keyword UPDATE, DELETE etc I checked are failing

**Comment by rkpunjal** [comment]
"select adf from abc",
                "insert into abcd",
                "update abcd",
                "delete from abcd",
                "upsert abcd",
                "call abcd",
                "rollback ",
                "create table abc",
                "drop table",
                "drop view",
                "alter table abc",
                "truncate table abc",
                "desc abc",

these and variations of these are still being called as bad data.

**Comment by rkpunjal** [comment]
only INSERT
or UPDATE
are not termed as malicious data

**Comment by shibinraj** [comment]
It were returning false before. 
The statement 'select id' is also valid . If I put 'select id from' then it return false. Is it ok?

**Comment by rkpunjal** [comment]
'select id' will be considered unsafe 
so 
`SqlSafeUtil.isSqlInjectionSafe("select id")`
will return `false`

and only INSERT, or only UPDATE, with nothing before and after that doesn't effect the data or db in any way. So it is considered as a safe data. 
eg 
insert into myTable(column1) values('INSERT');

This is a valid value and will does not result into sql injection of any kind.

**Comment by rkpunjal** [comment]
still let me know if you have any concerns

**Comment by shibinraj** [comment]
'select id' is returning true for me. and if it is like 'select id from' it will return false

**Comment by rkpunjal** [comment]
Okay, got your point. That's fixable, I shall fix it. Will msg soon.

**Comment by rkpunjal** [comment]
Fixed this now.

Use the Latest : 
```
<dependency>
  <groupId>com.github.rkpunjal.sqlsafe</groupId>
  <artifactId>sql-injection-safe</artifactId>
  <version>1.0.2</version>
</dependency>
```

Earlier 'select id from ...' and similar were considered malicious.
and 'select xx' was considered OK.

Hence created a new issue for this : https://github.com/rkpunjal/sql-injection-safe/issues/2

fixed it under that.
data like this will considered as malicious now
                "select id",
                "select 'abc'",

and 
SqlSafeUtil.isSqlInjectionSafe("select id") shall return false now
